<template><div><h1 id="学习-mvvm-发布订阅模式" tabindex="-1"><a class="header-anchor" href="#学习-mvvm-发布订阅模式" aria-hidden="true">#</a> 学习：MVVM 发布订阅模式</h1>
<h2 id="什么是发布订阅模式" tabindex="-1"><a class="header-anchor" href="#什么是发布订阅模式" aria-hidden="true">#</a> 什么是发布订阅模式</h2>
<p>定义：发布订阅模式是发布者不直接将消息发送给接收者（订阅者），而是将消息发给一个调度中心，调度中心根据消息的不同类别，向订阅者广播下去。</p>
<p>理解：称为发布者的消息发送者不会将消息直接发送给订阅者，这意味着发布者和订阅者不知道彼此的存在，二者没有消息往来。在发布者和订阅者之间存在第三个组件，称为消息代理或调度中心或中间件，它维持着发布者和订阅者之间的联系，过滤所有发布者传入的消息并相应地分发它们给订阅者。</p>
<p>需要注意的是：调度中心是管理着许许多多消息发布者的，调度中心的职责就是将发布者甲的消息准确地传输到发布者甲的各个订阅者处，将发布者乙的消息准确地传输到发布者乙的各个订阅者处。</p>
<p><img src="https://cdn.jsdelivr.net/gh/jsdevin/imgBed/img/202207220548808.png" alt="发布订阅模式详解"></p>
<h2 id="实现发布订阅模式" tabindex="-1"><a class="header-anchor" href="#实现发布订阅模式" aria-hidden="true">#</a> 实现发布订阅模式</h2>
<p>小练习：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token comment">//定义一家猎人工会  </span>
<span class="token comment">//主要功能包括任务发布大厅(topics)，以及订阅任务(subscribe)，发布任务(publish)  </span>
<span class="token keyword">let</span> HunterUnion <span class="token operator">=</span> <span class="token punctuation">{</span>  
	<span class="token literal-property property">type</span><span class="token operator">:</span> <span class="token string">'hunt'</span><span class="token punctuation">,</span>  
	<span class="token literal-property property">topics</span><span class="token operator">:</span> Object<span class="token punctuation">.</span><span class="token function">create</span><span class="token punctuation">(</span><span class="token keyword">null</span><span class="token punctuation">)</span><span class="token punctuation">,</span>  
	<span class="token function-variable function">subscribe</span><span class="token operator">:</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">topic<span class="token punctuation">,</span> fn</span><span class="token punctuation">)</span><span class="token punctuation">{</span> <span class="token comment">// 订阅  </span>
			<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token operator">!</span><span class="token keyword">this</span><span class="token punctuation">.</span>topics<span class="token punctuation">[</span>topic<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
					<span class="token keyword">this</span><span class="token punctuation">.</span>topics<span class="token punctuation">[</span>topic<span class="token punctuation">]</span> <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>    
			<span class="token punctuation">}</span>  
			<span class="token keyword">this</span><span class="token punctuation">.</span>topics<span class="token punctuation">[</span>topic<span class="token punctuation">]</span><span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>fn<span class="token punctuation">)</span><span class="token punctuation">;</span>  
	<span class="token punctuation">}</span><span class="token punctuation">,</span>  
	<span class="token function-variable function">publish</span><span class="token operator">:</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">topic<span class="token punctuation">,</span> money</span><span class="token punctuation">)</span><span class="token punctuation">{</span> <span class="token comment">// 发布  </span>
			<span class="token keyword">if</span><span class="token punctuation">(</span><span class="token operator">!</span><span class="token keyword">this</span><span class="token punctuation">.</span>topics<span class="token punctuation">[</span>topic<span class="token punctuation">]</span><span class="token punctuation">)</span>  
					<span class="token keyword">return</span><span class="token punctuation">;</span>  
			<span class="token keyword">for</span><span class="token punctuation">(</span><span class="token keyword">let</span> fn <span class="token keyword">of</span> <span class="token keyword">this</span><span class="token punctuation">.</span>topics<span class="token punctuation">[</span>topic<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
				<span class="token function">fn</span><span class="token punctuation">(</span>money<span class="token punctuation">)</span>  
			<span class="token punctuation">}</span>  
	<span class="token punctuation">}</span>  
<span class="token punctuation">}</span>  
  
<span class="token comment">//定义一个猎人类  </span>
<span class="token comment">//包括姓名，级别  </span>
<span class="token keyword">function</span> <span class="token function">Hunter</span><span class="token punctuation">(</span><span class="token parameter">name<span class="token punctuation">,</span> level</span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
	<span class="token keyword">this</span><span class="token punctuation">.</span>name <span class="token operator">=</span> name  
	<span class="token keyword">this</span><span class="token punctuation">.</span>level <span class="token operator">=</span> level  
<span class="token punctuation">}</span>  
<span class="token comment">//猎人可在猎人工会发布订阅任务  </span>
<span class="token class-name">Hunter</span><span class="token punctuation">.</span>prototype<span class="token punctuation">.</span><span class="token function-variable function">subscribe</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">topic<span class="token punctuation">,</span> fn</span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>level <span class="token operator">+</span> <span class="token string">'猎人'</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>name <span class="token operator">+</span> <span class="token string">'订阅了狩猎'</span> <span class="token operator">+</span> topic <span class="token operator">+</span> <span class="token string">'的任务'</span><span class="token punctuation">)</span>  
		HunterUnion<span class="token punctuation">.</span><span class="token function">subscribe</span><span class="token punctuation">(</span>topic<span class="token punctuation">,</span> fn<span class="token punctuation">)</span>  
<span class="token punctuation">}</span>  
<span class="token class-name">Hunter</span><span class="token punctuation">.</span>prototype<span class="token punctuation">.</span><span class="token function-variable function">publish</span> <span class="token operator">=</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">topic<span class="token punctuation">,</span> money</span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token keyword">this</span><span class="token punctuation">.</span>level <span class="token operator">+</span> <span class="token string">'猎人'</span> <span class="token operator">+</span> <span class="token keyword">this</span><span class="token punctuation">.</span>name <span class="token operator">+</span> <span class="token string">'发布了狩猎'</span> <span class="token operator">+</span> topic <span class="token operator">+</span> <span class="token string">'的任务'</span><span class="token punctuation">)</span>  
		HunterUnion<span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span>topic<span class="token punctuation">,</span> money<span class="token punctuation">)</span>  
<span class="token punctuation">}</span>  
  
<span class="token comment">//猎人工会走来了几个猎人  </span>
<span class="token keyword">let</span> hunterMing <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Hunter</span><span class="token punctuation">(</span><span class="token string">'小明'</span><span class="token punctuation">,</span> <span class="token string">'黄金'</span><span class="token punctuation">)</span>  
<span class="token keyword">let</span> hunterJin <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Hunter</span><span class="token punctuation">(</span><span class="token string">'小金'</span><span class="token punctuation">,</span> <span class="token string">'白银'</span><span class="token punctuation">)</span>  
<span class="token keyword">let</span> hunterZhang <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Hunter</span><span class="token punctuation">(</span><span class="token string">'小张'</span><span class="token punctuation">,</span> <span class="token string">'黄金'</span><span class="token punctuation">)</span>  
<span class="token keyword">let</span> hunterPeter <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">Hunter</span><span class="token punctuation">(</span><span class="token string">'Peter'</span><span class="token punctuation">,</span> <span class="token string">'青铜'</span><span class="token punctuation">)</span>  
  
<span class="token comment">//小明，小金，小张分别订阅了狩猎tiger的任务  </span>
hunterMing<span class="token punctuation">.</span><span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token string">'tiger'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">money</span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'小明表示：'</span> <span class="token operator">+</span> <span class="token punctuation">(</span>money <span class="token operator">></span> <span class="token number">200</span> <span class="token operator">?</span> <span class="token string">''</span> <span class="token operator">:</span> <span class="token string">'不'</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'接取任务'</span><span class="token punctuation">)</span>  
<span class="token punctuation">}</span><span class="token punctuation">)</span>  
hunterJin<span class="token punctuation">.</span><span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token string">'tiger'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">money</span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'小金表示：接取任务'</span><span class="token punctuation">)</span>  
<span class="token punctuation">}</span><span class="token punctuation">)</span>  
hunterZhang<span class="token punctuation">.</span><span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token string">'tiger'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">money</span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'小张表示：接取任务'</span><span class="token punctuation">)</span>  
<span class="token punctuation">}</span><span class="token punctuation">)</span>  
<span class="token comment">//Peter订阅了狩猎sheep的任务  </span>
hunterPeter<span class="token punctuation">.</span><span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token string">'sheep'</span><span class="token punctuation">,</span> <span class="token keyword">function</span><span class="token punctuation">(</span><span class="token parameter">money</span><span class="token punctuation">)</span><span class="token punctuation">{</span>  
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'Peter表示：接取任务'</span><span class="token punctuation">)</span>  
<span class="token punctuation">}</span><span class="token punctuation">)</span>  
  
<span class="token comment">//Peter发布了狩猎tiger的任务  </span>
hunterPeter<span class="token punctuation">.</span><span class="token function">publish</span><span class="token punctuation">(</span><span class="token string">'tiger'</span><span class="token punctuation">,</span> <span class="token number">198</span><span class="token punctuation">)</span>  
  
<span class="token comment">//猎人们发布(发布者)或订阅(观察者/订阅者)任务都是通过猎人工会(调度中心)关联起来的，他们没有直接的交流。  </span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>参考文章：</strong><br>
<a href="https://blog.csdn.net/weixin_35958891/article/details/108509048" target="_blank" rel="noopener noreferrer">参考1: 什么是发布订阅模式<ExternalLinkIcon/></a><br>
<a href="https://blog.csdn.net/weixin_35958891/article/details/108509048" target="_blank" rel="noopener noreferrer">参考2：观察者模式 vs 发布订阅模式<ExternalLinkIcon/></a></p>
</div></template>
